name: Docs

on:
#  push:
#    branches:
#    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Set up Pages
      uses: actions/configure-pages@v1
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
    - name: Generate Docs
      uses: fwcd/swift-docc-action@v1
      with:
        target: LegacyLogger
        output: ./docs
        hosting-base-path: Test-Repository
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: macos-13
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v1
